[build]
  publish = "./"
  command = ""

[redirects]
  # Redirect root domain to www
  [[redirects]]
    from = "https://epep.in/*"
    to = "https://www.epep.in/:splat"
    status = 301
    force = true

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/aboutus"
  to = "/aboutus.html"
  status = 200

# Already present — keep this at the end
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

